/**
 * v6.27.0: Invoice Template Engine
 * ================================
 * 5 professional invoice templates based on the sample PDFs:
 *   1. classic    — Monospace, black & white (current default)
 *   2. modern     — Clean sans-serif, navy accent, side-by-side parties
 *   3. minimal    — Ultra-clean, lots of whitespace, thin borders
 *   4. corporate  — Dark header bar, bold corporate look
 *   5. elegant    — Serif typography, gold accents, premium feel
 */

export interface InvoiceData {
  invoiceNumber: string
  date: string
  partyName: string
  partyAddress: string | null
  partyGst: string | null
  items: Array<{
    name: string
    category?: string
    hsn?: string
    unit?: string
    qty: number
    rate: number
    discount: number
    amount: number
    totalTax: number
    total: number
    saleItemType?: string
  }>
  subtotal: number
  gstAmount: number
  totalAmount: number
  amountReceived: number
  amountPaid: number
  discountPercent: number
  paymentStatus: string
  invoiceStatus: string
  notes: string | null
  upiAmount: number
}

export interface TenantData {
  name: string
  address?: string | null
  phone?: string | null
  email?: string | null
  gstNumber?: string | null
  upiId?: string | null
  logoUrl?: string | null
  invoiceColor?: string | null
  showLogoInInvoice?: boolean
  showSignatureInInvoice?: boolean
  showQrCode?: boolean
  invoiceFooterText?: string | null
}

function fmtCurrency(amt: number): string {
  return '₹' + Number(amt || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function fmtDate(dt: Date): string {
  return new Date(dt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

function normalizeStatus(s: string): string {
  const u = (s || '').toUpperCase()
  if (u === 'PAID' || u === 'RECEIVED') return 'RECEIVED'
  if (u === 'UNPAID' || u === 'PENDING') return 'PENDING'
  if (u === 'PARTIAL') return 'PARTIAL'
  return u
}

function statusLabel(s: string): string {
  const n = normalizeStatus(s)
  if (n === 'RECEIVED') return 'PAID'
  if (n === 'PENDING') return 'UNPAID'
  return n
}

function getDiscountInfo(sale: InvoiceData) {
  const discPercent = sale.discountPercent || 0
  const effectiveDiscount = sale.subtotal - (sale.totalAmount - sale.gstAmount)
  if (discPercent > 0) {
    const discAmt = Math.round(sale.subtotal * discPercent / 100 * 100) / 100
    const taxable = sale.subtotal - discAmt
    return { percent: discPercent, amount: discAmt, taxable }
  } else if (effectiveDiscount > 0.01) {
    const computedPercent = Math.round(effectiveDiscount / sale.subtotal * 100 * 10) / 10
    return { percent: computedPercent, amount: effectiveDiscount, taxable: sale.subtotal - effectiveDiscount }
  }
  return null
}

function getQrInfo(sale: InvoiceData, tenant: TenantData) {
  const upiId = tenant.upiId
  if (!upiId || tenant.showQrCode === false) return null
  const isQuotation = sale.invoiceStatus === 'QUOTATION'
  const balanceDue = sale.totalAmount - (sale.amountReceived || sale.amountPaid)
  const qrPayAmount = isQuotation
    ? (sale.upiAmount > 0 ? sale.upiAmount : sale.totalAmount)
    : balanceDue
  if (qrPayAmount <= 0) return null
  const qrUrl = 'https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=' +
    encodeURIComponent('upi://pay?pa=' + upiId + '&pn=' + (tenant.name || 'Business') + '&am=' + qrPayAmount + '&cu=INR&tn=Invoice ' + sale.invoiceNumber)
  return { url: qrUrl, amount: qrPayAmount }
}

// ============================================================
// TEMPLATE 1: CLASSIC (Monospace — current default)
// ============================================================
function templateClassic(sale: InvoiceData, tenant: TenantData): string {
  const disc = getDiscountInfo(sale)
  const qr = getQrInfo(sale, tenant)
  const logoHtml = tenant.logoUrl && tenant.showLogoInInvoice !== false
    ? `<img src="${tenant.logoUrl}" alt="Logo" style="max-height:80px;max-width:200px;margin-bottom:5px;object-fit:contain;" />` : ''
  const sigHtml = tenant.showSignatureInInvoice !== false
    ? `<div class="sig"><div class="line"></div><p>Authorised Signatory</p><small>For ${tenant.name || 'Business'}</small></div>` : ''
  const footerText = tenant.invoiceFooterText || `Computer-generated by BizBook Pro · Tahigo International · ${new Date().toLocaleString('en-IN')}`

  return `<!DOCTYPE html><html><head><title>Invoice - ${sale.invoiceNumber}</title>
<style>*{margin:0;padding:0;box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}@page{margin:5%}body{font-family:'Courier New',monospace;color:#000;width:90%;margin:0 auto;padding:2mm;font-weight:900}.header{text-align:center;margin-bottom:3mm;border-bottom:3px solid #000;padding-bottom:2mm}.header h1{font-size:20px;font-weight:900}.header p{font-size:11px;margin-top:2px;font-weight:900}.inv-meta{text-align:center;margin-bottom:3mm}.inv-meta .inv-no{font-size:16px;font-weight:900}.inv-meta .inv-date{font-size:12px;font-weight:700}.inv-meta .badge{display:inline-block;padding:3px 10px;border:2px solid #000;font-size:11px;font-weight:900;margin-top:2px}.parties{margin-bottom:3mm}.party .lbl{font-size:10px;text-transform:uppercase;font-weight:900;border-bottom:1px solid #000;padding-bottom:1px;margin-bottom:2px}.party .name{font-size:14px;font-weight:900}.party .detail{font-size:11px;font-weight:700}.items-header{display:flex;border-bottom:2px solid #000;padding-bottom:2px;margin-bottom:2px}.items-header .col-no{width:8%;font-size:10px;font-weight:900;text-transform:uppercase}.items-header .col-item{width:54%;font-size:10px;font-weight:900;text-transform:uppercase}.items-header .col-hsn{width:20%;font-size:10px;font-weight:900;text-transform:uppercase;text-align:center}.items-header .col-qty{width:18%;font-size:10px;font-weight:900;text-transform:uppercase;text-align:right}.item-row{display:flex;border-bottom:1px solid #000;padding:3px 0}.item-row .col-no{width:8%;font-size:11px;font-weight:700}.item-row .col-item{width:54%;font-size:11px;font-weight:700;word-break:break-word}.item-row .col-item .item-name{font-weight:900}.item-row .col-item .item-details{font-size:10px;margin-top:1px;font-weight:700}.item-row .col-hsn{width:20%;font-size:11px;font-weight:700;text-align:center;border:1px solid #000;margin:0 2px}.item-row .col-qty{width:18%;font-size:11px;font-weight:700;text-align:right}.totals{margin-bottom:3mm}.totals .row{display:flex;justify-content:space-between;padding:3px 0;font-size:12px;border-bottom:1px solid #000;font-weight:700}.totals .grand{font-size:15px;font-weight:900;border-top:3px solid #000;border-bottom:3px solid #000;padding:5px 0;margin-top:2px}.totals .due{font-weight:900}.notes{margin:2mm 0;padding:2mm;border:2px solid #000;font-size:11px;font-weight:700;word-break:break-word}.qr{text-align:center;margin:2mm 0}.qr img{width:80px;height:80px;border:2px solid #000}.qr .label{font-size:11px;font-weight:900;margin-top:2px}.sig{margin-top:4mm;text-align:center}.sig .line{border-top:2px solid #000;width:60%;margin:0 auto 2px}.sig p{font-size:11px;font-weight:900}.sig small{font-size:10px;font-weight:700}.footer{margin-top:4mm;padding-top:2mm;border-top:2px solid #000;text-align:center;font-size:10px;font-weight:700}@media print{@page{margin:5%}body{width:90%;padding:0}}</style>
</head><body>
<div class="header">${logoHtml}<h1>${tenant.name || 'BizBook Pro'}</h1>${tenant.address?`<p>${tenant.address}</p>`:''}${tenant.phone?`<p>Ph: ${tenant.phone}</p>`:''}${tenant.email?`<p>Email: ${tenant.email}</p>`:''}${tenant.gstNumber?`<p>GSTIN: ${tenant.gstNumber}</p>`:''}</div>
<div class="inv-meta"><div class="inv-no">#${sale.invoiceNumber}</div><div class="inv-date">${fmtDate(new Date(sale.date))}</div><div class="badge">${statusLabel(sale.paymentStatus)}</div></div>
<div class="parties"><div class="party"><div class="lbl">Bill To</div><div class="name">${sale.partyName}</div>${sale.partyAddress?`<div class="detail">${sale.partyAddress}</div>`:''}${sale.partyGst?`<div class="detail">GSTIN: ${sale.partyGst}</div>`:''}</div></div>
<div class="items-section"><div class="items-header"><div class="col-no">#</div><div class="col-item">Item</div><div class="col-hsn">HSN</div><div class="col-qty">Qty</div></div>
${sale.items.map((item,i)=>`<div class="item-row"><div class="col-no">${i+1}</div><div class="col-item"><div class="item-name">${item.name}${item.saleItemType==='SERVICE'?' [SVC]':''}${item.category?` <span style="font-size:10px;font-style:italic;font-weight:700;">(${item.category})</span>`:''}</div><div class="item-details">Rate: ${fmtCurrency(item.rate)} | Disc: ${item.discount>0?fmtCurrency(item.discount):'-'} | Amt: ${fmtCurrency(item.amount)} | Tax: ${fmtCurrency(item.totalTax)}</div><div class="item-details" style="font-weight:900;">Total: ${fmtCurrency(item.total)}</div></div><div class="col-hsn">${item.hsn||'-'}</div><div class="col-qty">${item.qty} ${item.unit||''}</div></div>`).join('')}
</div>
<div class="totals"><div class="row"><span>Subtotal</span><span>${fmtCurrency(sale.subtotal)}</span></div>${disc?`<div class="row"><span>Discount (${disc.percent}%)</span><span>-${fmtCurrency(disc.amount)}</span></div><div class="row"><span>Taxable Amount</span><span>${fmtCurrency(disc.taxable)}</span></div>`:''}<div class="row"><span>Tax</span><span>${fmtCurrency(sale.gstAmount)}</span></div><div class="row grand"><span>GRAND TOTAL</span><span>${fmtCurrency(sale.totalAmount)}</span></div><div class="row"><span>Received</span><span>${fmtCurrency(sale.amountReceived||sale.amountPaid)}</span></div><div class="row due"><span>Balance Due</span><span>${fmtCurrency(sale.totalAmount-(sale.amountReceived||sale.amountPaid))}</span></div></div>
${sale.notes?`<div class="notes"><strong>Notes:</strong> ${sale.notes}</div>`:''}
${qr?`<div class="qr"><img src="${qr.url}" alt="UPI QR" /><div class="label">Scan to Pay ${fmtCurrency(qr.amount)}</div></div>`:''}
${sigHtml}
<div class="footer">${footerText}</div>
<script>window.onload=function(){setTimeout(function(){window.print()},300)}</script>
</body></html>`
}

// ============================================================
// TEMPLATE 2: MODERN (Clean sans-serif, navy accent, side-by-side)
// ============================================================
function templateModern(sale: InvoiceData, tenant: TenantData): string {
  const disc = getDiscountInfo(sale)
  const qr = getQrInfo(sale, tenant)
  const accent = tenant.invoiceColor || '#001E42'
  const logoHtml = tenant.logoUrl && tenant.showLogoInInvoice !== false
    ? `<img src="${tenant.logoUrl}" alt="Logo" style="max-height:60px;max-width:180px;object-fit:contain;" />` : ''
  const sigHtml = tenant.showSignatureInInvoice !== false
    ? `<div style="margin-top:40px;display:flex;justify-content:space-between;"><div><div style="border-top:1px solid #ddd;width:200px;margin-bottom:5px;"></div><div style="font-size:10px;color:#888;">Authorised Signatory</div></div></div>` : ''
  const footerText = tenant.invoiceFooterText || `Computer-generated by BizBook Pro · ${new Date().toLocaleString('en-IN')}`

  return `<!DOCTYPE html><html><head><title>Invoice - ${sale.invoiceNumber}</title>
<style>*{margin:0;padding:0;box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}@page{margin:5%}body{font-family:'Segoe UI',Arial,sans-serif;color:#1a1a1a;width:90%;margin:0 auto;padding:20px}.hdr{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:30px;border-bottom:2px solid ${accent};padding-bottom:15px}.hdr-left{flex:1}.hdr-left h1{font-size:22px;color:${accent};margin-bottom:3px}.hdr-left p{font-size:11px;color:#888;line-height:1.5}.hdr-right{text-align:right}.hdr-right .inv-title{font-size:28px;font-weight:300;color:${accent};margin-bottom:5px}.hdr-right .inv-no{font-size:14px;color:#333;font-weight:600}.hdr-right .inv-date{font-size:11px;color:#888;margin-top:3px}.hdr-right .badge{display:inline-block;padding:3px 12px;border-radius:3px;font-size:10px;font-weight:600;margin-top:5px;color:#fff;background:${accent}}.parties{display:flex;gap:30px;margin-bottom:25px}.party-box{flex:1}.party-box .lbl{font-size:9px;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:5px;font-weight:600}.party-box .name{font-size:14px;font-weight:600;color:#333;margin-bottom:3px}.party-box .detail{font-size:11px;color:#666;line-height:1.5}.items-tbl{width:100%;border-collapse:collapse;margin-bottom:20px}.items-tbl th{background:${accent};color:#fff;font-size:10px;text-transform:uppercase;padding:8px 10px;text-align:left;font-weight:600}.items-tbl th.r{text-align:right}.items-tbl th.c{text-align:center}.items-tbl td{padding:8px 10px;font-size:11px;border-bottom:1px solid #eee;color:#333}.items-tbl td.r{text-align:right}.items-tbl td.c{text-align:center}.items-tbl tr:nth-child(even){background:#f9f9f9}.totals-box{float:right;width:300px;margin-bottom:20px}.totals-box .trow{display:flex;justify-content:space-between;padding:6px 0;font-size:12px;border-bottom:1px solid #eee}.totals-box .trow.grand{font-size:14px;font-weight:700;border-top:2px solid ${accent};border-bottom:2px solid ${accent};padding:8px 0;margin-top:3px;color:${accent}}.totals-box .trow.due{font-weight:600;color:#c0392b}.notes-box{clear:both;margin:15px 0;padding:10px;border:1px solid #eee;border-radius:4px;font-size:11px;color:#666}.qr-box{text-align:center;margin:15px 0}.qr-box img{width:80px;height:80px}.qr-box .lbl{font-size:10px;color:${accent};font-weight:600;margin-top:3px}.footer{margin-top:30px;padding-top:10px;border-top:1px solid #eee;text-align:center;font-size:9px;color:#999}</style>
</head><body>
<div class="hdr"><div class="hdr-left">${logoHtml}<h1>${tenant.name||'BizBook Pro'}</h1><p>${tenant.address||''}</p>${tenant.phone?`<p>Ph: ${tenant.phone}</p>`:''}${tenant.email?`<p>${tenant.email}</p>`:''}${tenant.gstNumber?`<p>GSTIN: ${tenant.gstNumber}</p>`:''}</div><div class="hdr-right"><div class="inv-title">INVOICE</div><div class="inv-no">#${sale.invoiceNumber}</div><div class="inv-date">${fmtDate(new Date(sale.date))}</div><div class="badge">${statusLabel(sale.paymentStatus)}</div></div></div>
<div class="parties"><div class="party-box"><div class="lbl">Billed From</div><div class="name">${tenant.name||'Business'}</div>${tenant.address?`<div class="detail">${tenant.address}</div>`:''}${tenant.gstNumber?`<div class="detail">GSTIN: ${tenant.gstNumber}</div>`:''}</div><div class="party-box"><div class="lbl">Billed To</div><div class="name">${sale.partyName}</div>${sale.partyAddress?`<div class="detail">${sale.partyAddress}</div>`:''}${sale.partyGst?`<div class="detail">GSTIN: ${sale.partyGst}</div>`:''}</div></div>
<table class="items-tbl"><thead><tr><th>#</th><th>Item Description</th><th class="c">HSN</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr></thead><tbody>
${sale.items.map((item,i)=>`<tr><td>${i+1}</td><td><strong>${item.name}${item.saleItemType==='SERVICE'?' [SVC]':''}</strong>${item.category?`<br/><span style="font-size:9px;color:#999;font-style:italic;">${item.category}</span>`:''}<br/><span style="font-size:9px;color:#999;">Disc: ${item.discount>0?fmtCurrency(item.discount):'-'} | Tax: ${fmtCurrency(item.totalTax)}</span></td><td class="c">${item.hsn||'-'}</td><td class="r">${item.qty} ${item.unit||''}</td><td class="r">${fmtCurrency(item.rate)}</td><td class="r"><strong>${fmtCurrency(item.total)}</strong></td></tr>`).join('')}
</tbody></table>
<div class="totals-box"><div class="trow"><span>Subtotal</span><span>${fmtCurrency(sale.subtotal)}</span></div>${disc?`<div class="trow"><span>Discount (${disc.percent}%)</span><span>-${fmtCurrency(disc.amount)}</span></div><div class="trow"><span>Taxable Amount</span><span>${fmtCurrency(disc.taxable)}</span></div>`:''}<div class="trow"><span>Tax</span><span>${fmtCurrency(sale.gstAmount)}</span></div><div class="trow grand"><span>GRAND TOTAL</span><span>${fmtCurrency(sale.totalAmount)}</span></div><div class="trow"><span>Received</span><span>${fmtCurrency(sale.amountReceived||sale.amountPaid)}</span></div><div class="trow due"><span>Balance Due</span><span>${fmtCurrency(sale.totalAmount-(sale.amountReceived||sale.amountPaid))}</span></div></div>
${sale.notes?`<div class="notes-box"><strong>Notes:</strong> ${sale.notes}</div>`:''}
${qr?`<div class="qr-box"><img src="${qr.url}" alt="UPI QR"/><div class="lbl">Scan to Pay ${fmtCurrency(qr.amount)}</div></div>`:''}
${sigHtml}
<div class="footer">${footerText}</div>
<div style="clear:both"></div>
<script>window.onload=function(){setTimeout(function(){window.print()},300)}</script>
</body></html>`
}

// ============================================================
// TEMPLATE 3: MINIMAL (Ultra-clean, lots of whitespace, thin borders)
// ============================================================
function templateMinimal(sale: InvoiceData, tenant: TenantData): string {
  const disc = getDiscountInfo(sale)
  const qr = getQrInfo(sale, tenant)
  const logoHtml = tenant.logoUrl && tenant.showLogoInInvoice !== false
    ? `<img src="${tenant.logoUrl}" alt="Logo" style="max-height:50px;max-width:150px;object-fit:contain;margin-bottom:10px;" />` : ''
  const sigHtml = tenant.showSignatureInInvoice !== false
    ? `<div style="margin-top:50px;text-align:right;"><div style="border-top:1px solid #ccc;width:180px;margin-left:auto;margin-bottom:5px;"></div><div style="font-size:10px;color:#999;">Authorised Signatory</div></div>` : ''
  const footerText = tenant.invoiceFooterText || `BizBook Pro · ${new Date().toLocaleString('en-IN')}`

  return `<!DOCTYPE html><html><head><title>Invoice - ${sale.invoiceNumber}</title>
<style>*{margin:0;padding:0;box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}@page{margin:8%}body{font-family:'Helvetica Neue',Arial,sans-serif;color:#333;width:84%;margin:0 auto;padding:20px}.top-bar{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:40px}.brand h1{font-size:18px;font-weight:300;color:#333;letter-spacing:0.5px}.brand p{font-size:10px;color:#bbb;margin-top:2px;line-height:1.6}.inv-meta{text-align:right}.inv-meta .title{font-size:14px;font-weight:300;color:#999;letter-spacing:2px;text-transform:uppercase}.inv-meta .no{font-size:13px;color:#333;margin-top:5px;font-weight:500}.inv-meta .date{font-size:10px;color:#bbb;margin-top:2px}.inv-meta .status{display:inline-block;padding:2px 10px;border:1px solid #ddd;border-radius:20px;font-size:9px;color:#999;margin-top:5px}.parties{display:flex;gap:50px;margin-bottom:35px}.p-box .lbl{font-size:8px;text-transform:uppercase;letter-spacing:1.5px;color:#ccc;margin-bottom:6px}.p-box .name{font-size:13px;font-weight:500;color:#333;margin-bottom:2px}.p-box .detail{font-size:10px;color:#999;line-height:1.5}.items{width:100%;border-collapse:collapse;margin-bottom:25px}.items th{font-size:8px;text-transform:uppercase;letter-spacing:1px;color:#ccc;padding:8px 5px;text-align:left;font-weight:500;border-bottom:1px solid #eee}.items th.r{text-align:right}.items th.c{text-align:center}.items td{padding:10px 5px;font-size:11px;color:#555;border-bottom:1px solid #f5f5f5}.items td.r{text-align:right}.items td.c{text-align:center}.items .item-name{font-weight:500;color:#333;font-size:12px}.items .item-sub{font-size:9px;color:#ccc;margin-top:1px}.totals{float:right;width:250px;margin-bottom:20px}.totals .t-row{display:flex;justify-content:space-between;padding:5px 0;font-size:11px;color:#999}.totals .t-row.grand{font-size:13px;font-weight:600;color:#333;border-top:1px solid #333;border-bottom:1px solid #333;padding:8px 0;margin-top:3px}.totals .t-row.due{color:#e74c3c;font-weight:500}.notes{clear:both;margin:15px 0;font-size:10px;color:#ccc;padding:8px 0;border-top:1px solid #f5f5f5}.qr{text-align:center;margin:15px 0}.qr img{width:70px;height:70px}.qr .lbl{font-size:9px;color:#999;margin-top:2px}.sig{margin-top:40px;text-align:right}.sig .line{border-top:1px solid #ddd;width:180px;margin-left:auto;margin-bottom:5px}.sig p{font-size:10px;color:#999}.footer{margin-top:35px;padding-top:10px;border-top:1px solid #f5f5f5;text-align:center;font-size:8px;color:#ddd}</style>
</head><body>
<div class="top-bar"><div class="brand">${logoHtml}<h1>${tenant.name||'BizBook Pro'}</h1><p>${tenant.address||''}</p>${tenant.phone?`<p>${tenant.phone}</p>`:''}${tenant.email?`<p>${tenant.email}</p>`:''}${tenant.gstNumber?`<p>GSTIN: ${tenant.gstNumber}</p>`:''}</div><div class="inv-meta"><div class="title">Invoice</div><div class="no">#${sale.invoiceNumber}</div><div class="date">${fmtDate(new Date(sale.date))}</div><div class="status">${statusLabel(sale.paymentStatus)}</div></div></div>
<div class="parties"><div class="p-box"><div class="lbl">From</div><div class="name">${tenant.name||'Business'}</div>${tenant.address?`<div class="detail">${tenant.address}</div>`:''}${tenant.gstNumber?`<div class="detail">GSTIN: ${tenant.gstNumber}</div>`:''}</div><div class="p-box"><div class="lbl">To</div><div class="name">${sale.partyName}</div>${sale.partyAddress?`<div class="detail">${sale.partyAddress}</div>`:''}${sale.partyGst?`<div class="detail">GSTIN: ${sale.partyGst}</div>`:''}</div></div>
<table class="items"><thead><tr><th>#</th><th>Description</th><th class="c">HSN</th><th class="r">Qty</th><th class="r">Rate</th><th class="r">Total</th></tr></thead><tbody>
${sale.items.map((item,i)=>`<tr><td class="c">${i+1}</td><td><div class="item-name">${item.name}${item.saleItemType==='SERVICE'?' [SVC]':''}</div>${item.category?`<div class="item-sub">${item.category}</div>`:''}<div class="item-sub">Disc: ${item.discount>0?fmtCurrency(item.discount):'-'} · Tax: ${fmtCurrency(item.totalTax)}</div></td><td class="c">${item.hsn||'-'}</td><td class="r">${item.qty} ${item.unit||''}</td><td class="r">${fmtCurrency(item.rate)}</td><td class="r"><strong>${fmtCurrency(item.total)}</strong></td></tr>`).join('')}
</tbody></table>
<div class="totals"><div class="t-row"><span>Subtotal</span><span>${fmtCurrency(sale.subtotal)}</span></div>${disc?`<div class="t-row"><span>Discount (${disc.percent}%)</span><span>-${fmtCurrency(disc.amount)}</span></div><div class="t-row"><span>Taxable Amount</span><span>${fmtCurrency(disc.taxable)}</span></div>`:''}<div class="t-row"><span>Tax</span><span>${fmtCurrency(sale.gstAmount)}</span></div><div class="t-row grand"><span>Grand Total</span><span>${fmtCurrency(sale.totalAmount)}</span></div><div class="t-row"><span>Received</span><span>${fmtCurrency(sale.amountReceived||sale.amountPaid)}</span></div><div class="t-row due"><span>Balance Due</span><span>${fmtCurrency(sale.totalAmount-(sale.amountReceived||sale.amountPaid))}</span></div></div>
${sale.notes?`<div class="notes"><strong>Notes:</strong> ${sale.notes}</div>`:''}
${qr?`<div class="qr"><img src="${qr.url}" alt="UPI QR"/><div class="lbl">Scan to Pay ${fmtCurrency(qr.amount)}</div></div>`:''}
${sigHtml}
<div class="footer">${footerText}</div>
<div style="clear:both"></div>
<script>window.onload=function(){setTimeout(function(){window.print()},300)}</script>
</body></html>`
}

// ============================================================
// TEMPLATE 4: CORPORATE (Dark header bar, bold corporate look)
// ============================================================
function templateCorporate(sale: InvoiceData, tenant: TenantData): string {
  const disc = getDiscountInfo(sale)
  const qr = getQrInfo(sale, tenant)
  const accent = tenant.invoiceColor || '#1e293b'
  const logoHtml = tenant.logoUrl && tenant.showLogoInInvoice !== false
    ? `<img src="${tenant.logoUrl}" alt="Logo" style="max-height:50px;max-width:160px;object-fit:contain;" />` : ''
  const sigHtml = tenant.showSignatureInInvoice !== false
    ? `<div style="margin-top:35px;display:flex;justify-content:flex-end;"><div style="text-align:center;"><div style="border-top:2px solid ${accent};width:180px;margin-bottom:5px;"></div><div style="font-size:10px;color:#666;font-weight:600;">Authorised Signatory</div></div></div>` : ''
  const footerText = tenant.invoiceFooterText || `Computer-generated by BizBook Pro · ${new Date().toLocaleString('en-IN')}`

  return `<!DOCTYPE html><html><head><title>Invoice - ${sale.invoiceNumber}</title>
<style>*{margin:0;padding:0;box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}@page{margin:0}body{font-family:'Segoe UI',Arial,sans-serif;color:#333}.hdr-bar{background:${accent};color:#fff;padding:25px 40px;display:flex;justify-content:space-between;align-items:center}.hdr-bar .brand h1{font-size:20px;font-weight:700;margin-bottom:2px}.hdr-bar .brand p{font-size:10px;opacity:0.8;line-height:1.5}.hdr-bar .inv-info{text-align:right}.hdr-bar .inv-info .title{font-size:24px;font-weight:300;letter-spacing:2px}.hdr-bar .inv-info .no{font-size:14px;margin-top:3px;font-weight:600}.hdr-bar .inv-info .date{font-size:10px;opacity:0.7;margin-top:2px}.hdr-bar .inv-info .status{display:inline-block;padding:2px 10px;border:1px solid rgba(255,255,255,0.3);border-radius:3px;font-size:9px;margin-top:4px}.content{padding:25px 40px}.parties{display:flex;gap:30px;margin-bottom:20px}.p-box{flex:1;padding:12px;border:1px solid #eee;border-left:3px solid ${accent};border-radius:0 4px 4px 0}.p-box .lbl{font-size:8px;text-transform:uppercase;letter-spacing:1px;color:#999;margin-bottom:5px;font-weight:700}.p-box .name{font-size:13px;font-weight:700;color:#333;margin-bottom:2px}.p-box .detail{font-size:10px;color:#777;line-height:1.5}.items-tbl{width:100%;border-collapse:collapse;margin-bottom:20px}.items-tbl th{background:#f5f5f5;font-size:9px;text-transform:uppercase;padding:8px;font-weight:700;color:#555;text-align:left;border-bottom:2px solid ${accent}}.items-tbl th.r{text-align:right}.items-tbl th.c{text-align:center}.items-tbl td{padding:8px;font-size:11px;border-bottom:1px solid #eee}.items-tbl td.r{text-align:right}.items-tbl td.c{text-align:center}.totals-area{float:right;width:280px;margin-bottom:15px}.totals-area .t-row{display:flex;justify-content:space-between;padding:5px 0;font-size:11px;color:#666;border-bottom:1px solid #f0f0f0}.totals-area .t-row.grand{font-size:14px;font-weight:700;color:${accent};border-top:2px solid ${accent};border-bottom:2px solid ${accent};padding:8px 0;margin-top:3px}.totals-area .t-row.due{color:#c0392b;font-weight:600}.notes-area{clear:both;margin:12px 0;padding:10px;border:1px solid #eee;border-radius:4px;font-size:10px;color:#888}.qr-area{text-align:center;margin:12px 0}.qr-area img{width:75px;height:75px}.qr-area .lbl{font-size:10px;color:${accent};font-weight:600;margin-top:2px}.footer-bar{background:#f5f5f5;padding:12px 40px;text-align:center;font-size:9px;color:#999;border-top:1px solid #eee}</style>
</head><body>
<div class="hdr-bar"><div class="brand">${logoHtml}<h1>${tenant.name||'BizBook Pro'}</h1><p>${tenant.address||''}</p>${tenant.phone?`<p>Ph: ${tenant.phone}</p>`:''}${tenant.email?`<p>${tenant.email}</p>`:''}${tenant.gstNumber?`<p>GSTIN: ${tenant.gstNumber}</p>`:''}</div><div class="inv-info"><div class="title">TAX INVOICE</div><div class="no">#${sale.invoiceNumber}</div><div class="date">${fmtDate(new Date(sale.date))}</div><div class="status">${statusLabel(sale.paymentStatus)}</div></div></div>
<div class="content">
<div class="parties"><div class="p-box"><div class="lbl">Service Provider</div><div class="name">${tenant.name||'Business'}</div>${tenant.address?`<div class="detail">${tenant.address}</div>`:''}${tenant.gstNumber?`<div class="detail">GSTIN: ${tenant.gstNumber}</div>`:''}</div><div class="p-box"><div class="lbl">Customer Details</div><div class="name">${sale.partyName}</div>${sale.partyAddress?`<div class="detail">${sale.partyAddress}</div>`:''}${sale.partyGst?`<div class="detail">GSTIN: ${sale.partyGst}</div>`:''}</div></div>
<table class="items-tbl"><thead><tr><th>#</th><th>Item Description</th><th class="c">HSN</th><th class="c">Qty</th><th class="r">Rate (₹)</th><th class="r">Amount (₹)</th></tr></thead><tbody>
${sale.items.map((item,i)=>`<tr><td class="c">${i+1}</td><td><strong>${item.name}${item.saleItemType==='SERVICE'?' [SVC]':''}</strong>${item.category?`<br/><span style="font-size:9px;color:#aaa;font-style:italic;">${item.category}</span>`:''}<br/><span style="font-size:9px;color:#aaa;">Disc: ${item.discount>0?fmtCurrency(item.discount):'-'} · Tax: ${fmtCurrency(item.totalTax)}</span></td><td class="c">${item.hsn||'-'}</td><td class="c">${item.qty} ${item.unit||''}</td><td class="r">${fmtCurrency(item.rate)}</td><td class="r"><strong>${fmtCurrency(item.total)}</strong></td></tr>`).join('')}
</tbody></table>
<div class="totals-area"><div class="t-row"><span>Subtotal</span><span>${fmtCurrency(sale.subtotal)}</span></div>${disc?`<div class="t-row"><span>Discount (${disc.percent}%)</span><span>-${fmtCurrency(disc.amount)}</span></div><div class="t-row"><span>Taxable Amount</span><span>${fmtCurrency(disc.taxable)}</span></div>`:''}<div class="t-row"><span>Tax</span><span>${fmtCurrency(sale.gstAmount)}</span></div><div class="t-row grand"><span>GRAND TOTAL</span><span>${fmtCurrency(sale.totalAmount)}</span></div><div class="t-row"><span>Received</span><span>${fmtCurrency(sale.amountReceived||sale.amountPaid)}</span></div><div class="t-row due"><span>Balance Due</span><span>${fmtCurrency(sale.totalAmount-(sale.amountReceived||sale.amountPaid))}</span></div></div>
${sale.notes?`<div class="notes-area"><strong>Notes:</strong> ${sale.notes}</div>`:''}
${qr?`<div class="qr-area"><img src="${qr.url}" alt="UPI QR"/><div class="lbl">Scan to Pay ${fmtCurrency(qr.amount)}</div></div>`:''}
${sigHtml}
</div>
<div style="clear:both"></div>
<div class="footer-bar">${footerText}</div>
<script>window.onload=function(){setTimeout(function(){window.print()},300)}</script>
</body></html>`
}

// ============================================================
// TEMPLATE 5: ELEGANT (Serif typography, premium feel)
// ============================================================
function templateElegant(sale: InvoiceData, tenant: TenantData): string {
  const disc = getDiscountInfo(sale)
  const qr = getQrInfo(sale, tenant)
  const accent = tenant.invoiceColor || '#8B7355'
  const logoHtml = tenant.logoUrl && tenant.showLogoInInvoice !== false
    ? `<img src="${tenant.logoUrl}" alt="Logo" style="max-height:55px;max-width:170px;object-fit:contain;margin-bottom:8px;" />` : ''
  const sigHtml = tenant.showSignatureInInvoice !== false
    ? `<div style="margin-top:40px;text-align:right;"><div style="border-bottom:1px solid ${accent};width:200px;margin-left:auto;margin-bottom:5px;"></div><div style="font-size:11px;color:#999;font-family:Georgia,serif;font-style:italic;">Authorised Signatory</div></div>` : ''
  const footerText = tenant.invoiceFooterText || `Computer-generated by BizBook Pro · ${new Date().toLocaleString('en-IN')}`

  return `<!DOCTYPE html><html><head><title>Invoice - ${sale.invoiceNumber}</title>
<style>*{margin:0;padding:0;box-sizing:border-box;-webkit-print-color-adjust:exact;print-color-adjust:exact}@page{margin:6%}body{font-family:Georgia,'Times New Roman',serif;color:#2c2c2c;width:88%;margin:0 auto;padding:20px}.hdr{text-align:center;margin-bottom:30px;padding-bottom:15px;border-bottom:2px double ${accent}}.hdr h1{font-size:24px;font-weight:normal;color:${accent};letter-spacing:1px;margin-bottom:3px}.hdr p{font-size:11px;color:#999;line-height:1.6}.inv-center{text-align:center;margin-bottom:25px}.inv-center .title{font-size:16px;text-transform:uppercase;letter-spacing:3px;color:${accent};margin-bottom:5px}.inv-center .no{font-size:14px;color:#333;font-weight:bold}.inv-center .date{font-size:11px;color:#999;margin-top:2px}.inv-center .status{display:inline-block;padding:3px 15px;border:1px solid ${accent};border-radius:15px;font-size:10px;color:${accent};margin-top:5px;font-style:italic}.parties{display:flex;gap:40px;margin-bottom:25px;justify-content:center}.p-box{text-align:center;flex:1}.p-box .lbl{font-size:9px;text-transform:uppercase;letter-spacing:2px;color:#ccc;margin-bottom:5px}.p-box .name{font-size:14px;color:#333;font-weight:bold;margin-bottom:2px}.p-box .detail{font-size:10px;color:#999;line-height:1.5}.items-tbl{width:100%;border-collapse:collapse;margin-bottom:20px}.items-tbl th{font-size:9px;text-transform:uppercase;letter-spacing:1px;color:${accent};padding:8px;text-align:left;border-bottom:2px solid ${accent};font-weight:normal}.items-tbl th.r{text-align:right}.items-tbl th.c{text-align:center}.items-tbl td{padding:8px;font-size:11px;border-bottom:1px solid #f0f0f0;color:#555}.items-tbl td.r{text-align:right}.items-tbl td.c{text-align:center}.items-tbl .item-name{font-weight:bold;color:#333;font-size:12px}.totals{float:right;width:280px;margin-bottom:15px}.totals .t-row{display:flex;justify-content:space-between;padding:5px 0;font-size:12px;color:#777;border-bottom:1px solid #f5f5f5}.totals .t-row.grand{font-size:15px;font-weight:bold;color:${accent};border-top:2px solid ${accent};border-bottom:2px solid ${accent};padding:8px 0;margin-top:3px}.totals .t-row.due{color:#c0392b;font-weight:bold}.notes{clear:both;margin:15px 0;padding:10px;border:1px dashed #ddd;font-size:11px;color:#999;font-style:italic}.qr{text-align:center;margin:15px 0}.qr img{width:75px;height:75px}.qr .lbl{font-size:10px;color:${accent};font-style:italic;margin-top:2px}.footer{margin-top:30px;padding-top:10px;border-top:1px solid #f0f0f0;text-align:center;font-size:9px;color:#ccc;font-style:italic}</style>
</head><body>
<div class="hdr">${logoHtml}<h1>${tenant.name||'BizBook Pro'}</h1><p>${tenant.address||''}</p>${tenant.phone?`<p>Ph: ${tenant.phone}</p>`:''}${tenant.email?`<p>${tenant.email}</p>`:''}${tenant.gstNumber?`<p>GSTIN: ${tenant.gstNumber}</p>`:''}</div>
<div class="inv-center"><div class="title">Invoice</div><div class="no">#${sale.invoiceNumber}</div><div class="date">${fmtDate(new Date(sale.date))}</div><div class="status">${statusLabel(sale.paymentStatus)}</div></div>
<div class="parties"><div class="p-box"><div class="lbl">From</div><div class="name">${tenant.name||'Business'}</div>${tenant.address?`<div class="detail">${tenant.address}</div>`:''}${tenant.gstNumber?`<div class="detail">GSTIN: ${tenant.gstNumber}</div>`:''}</div><div class="p-box"><div class="lbl">To</div><div class="name">${sale.partyName}</div>${sale.partyAddress?`<div class="detail">${sale.partyAddress}</div>`:''}${sale.partyGst?`<div class="detail">GSTIN: ${sale.partyGst}</div>`:''}</div></div>
<table class="items-tbl"><thead><tr><th>#</th><th>Description</th><th class="c">HSN</th><th class="c">Qty</th><th class="r">Rate</th><th class="r">Amount</th></tr></thead><tbody>
${sale.items.map((item,i)=>`<tr><td class="c">${i+1}</td><td><div class="item-name">${item.name}${item.saleItemType==='SERVICE'?' [SVC]':''}</div>${item.category?`<div style="font-size:9px;color:#bbb;font-style:italic;">${item.category}</div>`:''}<div style="font-size:9px;color:#bbb;">Disc: ${item.discount>0?fmtCurrency(item.discount):'-'} · Tax: ${fmtCurrency(item.totalTax)}</div></td><td class="c">${item.hsn||'-'}</td><td class="c">${item.qty} ${item.unit||''}</td><td class="r">${fmtCurrency(item.rate)}</td><td class="r"><strong>${fmtCurrency(item.total)}</strong></td></tr>`).join('')}
</tbody></table>
<div class="totals"><div class="t-row"><span>Subtotal</span><span>${fmtCurrency(sale.subtotal)}</span></div>${disc?`<div class="t-row"><span>Discount (${disc.percent}%)</span><span>-${fmtCurrency(disc.amount)}</span></div><div class="t-row"><span>Taxable Amount</span><span>${fmtCurrency(disc.taxable)}</span></div>`:''}<div class="t-row"><span>Tax</span><span>${fmtCurrency(sale.gstAmount)}</span></div><div class="t-row grand"><span>Total Due</span><span>${fmtCurrency(sale.totalAmount)}</span></div><div class="t-row"><span>Received</span><span>${fmtCurrency(sale.amountReceived||sale.amountPaid)}</span></div><div class="t-row due"><span>Balance Due</span><span>${fmtCurrency(sale.totalAmount-(sale.amountReceived||sale.amountPaid))}</span></div></div>
${sale.notes?`<div class="notes"><strong>Notes:</strong> ${sale.notes}</div>`:''}
${qr?`<div class="qr"><img src="${qr.url}" alt="UPI QR"/><div class="lbl">Scan to Pay ${fmtCurrency(qr.amount)}</div></div>`:''}
${sigHtml}
<div class="footer">${footerText}</div>
<div style="clear:both"></div>
<script>window.onload=function(){setTimeout(function(){window.print()},300)}</script>
</body></html>`
}

// ============================================================
// MAIN: Template selector
// ============================================================
export function generateInvoiceHtml(sale: InvoiceData, tenant: TenantData): string {
  const template = tenant.invoiceTemplate || 'classic'
  switch (template) {
    case 'modern': return templateModern(sale, tenant)
    case 'minimal': return templateMinimal(sale, tenant)
    case 'corporate': return templateCorporate(sale, tenant)
    case 'elegant': return templateElegant(sale, tenant)
    default: return templateClassic(sale, tenant)
  }
}

export const INVOICE_TEMPLATES = [
  { value: 'classic', label: 'Classic (Monospace — black & white)' },
  { value: 'modern', label: 'Modern (Sans-serif — navy accent, side-by-side)' },
  { value: 'minimal', label: 'Minimal (Ultra-clean — lots of whitespace)' },
  { value: 'corporate', label: 'Corporate (Dark header bar — bold)' },
  { value: 'elegant', label: 'Elegant (Serif — gold accent, premium)' },
]
