/**
 * v4.152: IRP (Invoice Registration Portal) Integration Library
 * ============================================================
 * Direct integration with the Indian GST IRP for e-invoice generation.
 *
 * Flow:
 *   1. Tenant configures GSP (GST Suvidha Provider) credentials in Settings
 *   2. We authenticate with IRP via the GSP and receive a bearer token (valid 60 min)
 *   3. For each B2B invoice, we generate the INV-01 JSON payload (already implemented)
 *   4. We sign the payload with the tenant's digital signature (optional — IRP accepts unsigned for GSP route)
 *   5. POST to /einvoice/api/v1/einvoice (IRP API) → returns IRN + AckNo + AckDate + SignedQR
 *   6. Persist these fields on the Sale record
 *
 * Environment variables:
 *   - IRP_GSP_CODE: GSP identifier (e.g. 'clear', 'adaequare', ' Mastersindia')
 *   - IRP_GSP_USERNAME: GSP-issued username
 *   - IRP_GSP_PASSWORD: GSP-issued password
 *   - IRP_GSP_CLIENT_ID: GSP-issued client ID
 *   - IRP_GSP_CLIENT_SECRET: GSP-issued client secret
 *   - IRP_ENV: 'sandbox' or 'production' (default: sandbox)
 *
 * Sandbox URL: https://einvoice1.traces.gov.in
 * Production URL: https://einvoice.gst.gov.in
 *
 * If GSP credentials are not configured, the API returns MANUAL mode — user copies
 * the INV-01 JSON, submits it manually to the IRP portal, then pastes back IRN/AckNo.
 *
 * References:
 *   - https://einvoice1.traces.gov.in/IrpFileDownload/Web/HelpMultipage.htm
 *   - IRN cancellation window: 24 hours from generation
 *   - IRN format: 64-character hex string
 */

import crypto from 'crypto'

const IRP_SANDBOX_URL = 'https://einvoice1.traces.gov.in'
const IRP_PRODUCTION_URL = 'https://einvoice.gst.gov.in'

function getIrpBaseUrl(): string {
  return process.env.IRP_ENV === 'production' ? IRP_PRODUCTION_URL : IRP_SANDBOX_URL
}

function isIrpConfigured(): boolean {
  return !!(
    process.env.IRP_GSP_CODE &&
    process.env.IRP_GSP_CLIENT_ID &&
    process.env.IRP_GSP_CLIENT_SECRET
  )
}

interface GspAuthResponse {
  access_token: string
  token_type: string
  expires_in: number
  scope: string
}

// Cache the auth token (valid 60 min, we refresh at 50 min)
let cachedToken: { token: string; expiresAt: number } | null = null

/**
 * Authenticate with IRP via GSP — returns bearer token valid for 60 minutes.
 * Cache is shared across all requests in the process.
 */
async function getIrpAuthToken(): Promise<string> {
  // Return cached token if still valid (with 5-min safety buffer)
  if (cachedToken && Date.now() < cachedToken.expiresAt - 5 * 60 * 1000) {
    return cachedToken.token
  }

  const baseUrl = getIrpBaseUrl()
  const gspCode = process.env.IRP_GSP_CODE
  const clientId = process.env.IRP_GSP_CLIENT_ID
  const clientSecret = process.env.IRP_GSP_CLIENT_SECRET
  const username = process.env.IRP_GSP_USERNAME
  const password = process.env.IRP_GSP_PASSWORD

  // Step 1: Get GSP auth token (used to call IRP)
  const authPayload = {
    Username: username,
    Password: password,
    ClientId: clientId,
    ClientSecret: clientSecret,
    GrantType: 'password',
  }

  const authRes = await fetch(`${baseUrl}/ein-v1/registration/authenticate`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'gsp-code': gspCode!,
    },
    body: JSON.stringify(authPayload),
  })

  if (!authRes.ok) {
    const errText = await authRes.text()
    throw new Error(`IRP auth failed (HTTP ${authRes.status}): ${errText}`)
  }

  const authData: GspAuthResponse = await authRes.json()
  cachedToken = {
    token: authData.access_token,
    expiresAt: Date.now() + authData.expires_in * 1000,
  }

  return cachedToken.token
}

export interface IrpSubmitResult {
  success: boolean
  irn?: string
  ackNo?: string
  ackDate?: string
  signedQrCode?: string
  errorMessage?: string
  mode: 'LIVE' | 'MANUAL'
}

/**
 * Submit an INV-01 payload to IRP for IRN generation.
 *
 * @param inv01Payload — the JSON payload generated by /api/einvoice generate-payload
 * @returns IrpSubmitResult with IRN + AckNo on success, or MANUAL mode flag
 */
export async function submitToIrp(inv01Payload: any): Promise<IrpSubmitResult> {
  // If GSP not configured, return MANUAL mode
  if (!isIrpConfigured()) {
    return {
      success: false,
      mode: 'MANUAL',
      errorMessage: 'IRP not configured. Submit the INV-01 payload manually to the IRP portal, then paste back IRN/AckNo.',
    }
  }

  try {
    const token = await getIrpAuthToken()
    const baseUrl = getIrpBaseUrl()

    const res = await fetch(`${baseUrl}/einvoice/api/v1/einvoice`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'gsp-code': process.env.IRP_GSP_CODE!,
      },
      body: JSON.stringify(inv01Payload),
    })

    if (!res.ok) {
      const errText = await res.text()
      return {
        success: false,
        mode: 'LIVE',
        errorMessage: `IRP HTTP ${res.status}: ${errText.slice(0, 500)}`,
      }
    }

    const data = await res.json()

    // IRP success response shape:
    // {
    //   "Message": "IRN generated successfully",
    //   "Status": 1,
    //   "Result": {
    //     "AckNo": 123456789012345,
    //     "AckDt": "2024-01-15 14:30:00",
    //     "Irn": "abc123...xyz (64 hex chars)",
    //     "SignedInvoice": "...",
    //     "SignedQRCode": "..."
    //   },
    //   "Info": [...]
    // }
    if (data.Status === 1 || data.Status === '1') {
      return {
        success: true,
        mode: 'LIVE',
        irn: data.Result?.Irn,
        ackNo: String(data.Result?.AckNo || ''),
        ackDate: data.Result?.AckDt,
        signedQrCode: data.Result?.SignedQRCode,
      }
    }

    // IRP returned an error (Status 0)
    const errorMessages = (data.ErrorDetails || []).map((e: any) => e.ErrorMessage).join('; ')
    return {
      success: false,
      mode: 'LIVE',
      errorMessage: errorMessages || data.Message || 'Unknown IRP error',
    }
  } catch (err: any) {
    return {
      success: false,
      mode: 'LIVE',
      errorMessage: `Network error: ${err?.message || 'Unknown'}`,
    }
  }
}

/**
 * Cancel an existing IRN on IRP.
 * Allowed within 24 hours of generation.
 * @param irn — the 64-char IRN to cancel
 * @param reason — reason code (1-6 per IRP spec)
 */
export async function cancelIrn(irn: string, reason: string): Promise<IrpSubmitResult> {
  if (!isIrpConfigured()) {
    return {
      success: false,
      mode: 'MANUAL',
      errorMessage: 'IRP not configured. Cancel the IRN manually on the IRP portal.',
    }
  }

  try {
    const token = await getIrpAuthToken()
    const baseUrl = getIrpBaseUrl()

    const res = await fetch(`${baseUrl}/einvoice/api/v1/einvoice/cancel`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'gsp-code': process.env.IRP_GSP_CODE!,
      },
      body: JSON.stringify({ Irb: irn, CnlRsn: reason, CnlRem: 'Cancelled via BizBook Pro' }),
    })

    if (!res.ok) {
      const errText = await res.text()
      return {
        success: false,
        mode: 'LIVE',
        errorMessage: `IRP cancel HTTP ${res.status}: ${errText.slice(0, 500)}`,
      }
    }

    const data = await res.json()
    if (data.Status === 1 || data.Status === '1') {
      return { success: true, mode: 'LIVE' }
    }

    const errorMessages = (data.ErrorDetails || []).map((e: any) => e.ErrorMessage).join('; ')
    return {
      success: false,
      mode: 'LIVE',
      errorMessage: errorMessages || 'IRN cancellation failed',
    }
  } catch (err: any) {
    return {
      success: false,
      mode: 'LIVE',
      errorMessage: `Network error: ${err?.message || 'Unknown'}`,
    }
  }
}

/**
 * Get IRN details from IRP (e.g. to verify a pasted-back IRN is real).
 */
export async function getIrnDetails(irn: string): Promise<IrpSubmitResult & { data?: any }> {
  if (!isIrpConfigured()) {
    return {
      success: false,
      mode: 'MANUAL',
      errorMessage: 'IRP not configured.',
    }
  }

  try {
    const token = await getIrpAuthToken()
    const baseUrl = getIrpBaseUrl()

    const res = await fetch(`${baseUrl}/einvoice/api/v1/einvoice/irn/${irn}`, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${token}`,
        'gsp-code': process.env.IRP_GSP_CODE!,
      },
    })

    if (!res.ok) {
      return {
        success: false,
        mode: 'LIVE',
        errorMessage: `IRP get HTTP ${res.status}`,
      }
    }

    const data = await res.json()
    return {
      success: data.Status === 1 || data.Status === '1',
      mode: 'LIVE',
      irn: data.Result?.Irn,
      ackNo: String(data.Result?.AckNo || ''),
      ackDate: data.Result?.AckDt,
      signedQrCode: data.Result?.SignedQRCode,
      data: data.Result,
    }
  } catch (err: any) {
    return {
      success: false,
      mode: 'LIVE',
      errorMessage: `Network error: ${err?.message || 'Unknown'}`,
    }
  }
}

export { isIrpConfigured, getIrpBaseUrl }
