import { NextRequest, NextResponse } from 'next/server'
import ZAI from 'z-ai-web-dev-sdk'
import { db } from '@/lib/db-soft-delete'
import { writeFile, mkdir } from 'fs/promises'
import { join } from 'path'
import { randomUUID } from 'crypto'
import { requireAuthAndTenant, requireAuthAndRole, requireAuth, writeAuditLog } from '@/lib/api-helpers'

export const maxDuration = 300

const UPLOAD_DIR = join(process.cwd(), 'upload')

async function ensureUploadDir() {
  await mkdir(UPLOAD_DIR, { recursive: true })
}

const ANALYSIS_SYSTEM_PROMPT = `You are an expert business data analyst working with BizBook Pro accounting software.

Your job is to analyze uploaded business data files and extract structured data for import into BizBook Pro.

Users may maintain their business data across multiple files in different formats — expenses in Word, purchases in Excel, inventory in another file, party details in CSV, bill images, etc. Each file is analyzed independently and then merged.

BizBook Pro data modules (use EXACT field names as shown):
1. **Sales**: date(YYYY-MM-DD), invoiceNumber, partyName, partyAddress, partyGst, items(JSON array of {name,hsn,qty,rate,gstRate,amount}), subtotal, gstAmount, totalAmount, paymentStatus(PENDING/PARTIAL/RECEIVED), amountReceived, notes
2. **Purchases**: date(YYYY-MM-DD), invoiceNumber, partyName, partyAddress, partyGst, items(JSON array of {name,hsn,qty,rate,gstRate,amount}), subtotal, gstAmount, totalAmount, paymentStatus(UNPAID/PARTIAL/PAID), amountPaid, notes
3. **Expenses**: date(YYYY-MM-DD), description, category, amount, paymentMode(CASH/BANK/UPI/CARD), reference, notes
4. **Products/Inventory**: name, sku, category, hsnCode, unit, purchasePrice, salePrice, mrp, gstRate, currentStock, brand, itemType(RAW_MATERIAL/FINISHED_PRODUCT)
5. **Parties** (customers/suppliers): name, type(CUSTOMER/SUPPLIER/BOTH), phone, email, address, gstNumber, panNumber, openingBalance
6. **Staff**: name, phone, email, role, department, salary, address, aadhaar, pan
7. **Bank Transactions**: date(YYYY-MM-DD), description, deposit(0 if withdrawal), withdrawal(0 if deposit), balance, reference, category, bankName, accountNumber

RULES:
- Extract ALL business-relevant data from the file content provided below
- Auto-generate missing fields (invoice numbers if absent, assign default GST 18%)
- Calculate totals from line items when available
- Handle Indian GST (CGST+SGST or IGST)
- Dates in YYYY-MM-DD format, amounts as numbers
- For bank transactions: if amount is positive/credit, set deposit=amount, withdrawal=0. If negative/debit, set withdrawal=abs(amount), deposit=0
- If data seems ambiguous, extract it anyway with a warning
- Be thorough — even unusual file formats may contain important business data
- Use EXACT field names as listed above, do NOT use aliases

CRITICAL — SALE vs PURCHASE INVOICE CLASSIFICATION:
The user uploading the file is a BUSINESS OWNER using BizBook Pro to manage THEIR business.

A **SALE INVOICE** (detectedDocumentType = "sale_invoice") is:
- An invoice generated BY the user's business TO their customer
- The user's business is the SELLER/SUPPLIER
- The party (buyer/customer) owes money TO the user's business
- Keywords: "Sold to", "Buyer", "Billed to", "Customer", "Consignee"
- The seller's GSTIN/company name matches the user's business
- Sale GST/non-GST invoices are ALWAYS generated by BizBook Pro (the user's business)

A **PURCHASE INVOICE** (detectedDocumentType = "purchase_invoice") is:
- An invoice generated BY a SUPPLIER from whom the user purchases raw materials/goods
- The user's business is the BUYER/PURCHASER
- The user's business owes money TO the supplier
- Keywords: "Sold by", "Seller", "Vendor", "Supplier", "From", "Supplier Invoice"
- The buyer's GSTIN/company name matches the user's business
- Purchase invoices are ALWAYS created by the SUPPLIER, NOT by the user's business

KEY DISTINCTION: Look at WHO issued the document:
- If the document was ISSUED BY the supplier (their name/GSTIN is at the top as seller) → it's a PURCHASE INVOICE
- If the document was ISSUED BY the user's business (their name/GSTIN is at the top as seller) → it's a SALE INVOICE
- When the seller's name is a DIFFERENT company from the user's business → it's a PURCHASE INVOICE (the user bought from that supplier)
- When the buyer's name is a DIFFERENT company from the user's business → it's a SALE INVOICE (the user sold to that customer)

IMPORTANT: You MUST identify the primary document type from the content. Use these exact values for detectedDocumentType:
  - "sale_invoice" — invoices where the user's business is the SELLER (user sold goods/services to a customer)
  - "purchase_invoice" — invoices where the user's business is the BUYER (user purchased goods/services from a supplier)
  - "bank_statement" — bank statements, bank passbook, bank transaction records, credit/debit statements
  - "inventory_data" — product lists, stock registers, inventory sheets, price lists with stock
  - "expense_data" — expense records, receipts, payment vouchers, expense reports
  - "staff_data" — employee lists, payroll data, staff records
  - "party_data" — customer lists, supplier lists, contact lists, CRM data
  - "backup_data" — full backup exports from Tally/Zoho/other accounting software with multiple modules (multiple sheet names like "Sales", "Purchases", "Inventory" etc.)
  - "mixed_data" — when the file clearly contains data for multiple different modules and no single type dominates
  - "unknown" — only if you truly cannot determine the type

RESPONSE FORMAT — Return ONLY valid JSON:
{
  "fileName": "original filename",
  "fileType": "invoice|product-list|party-list|expense|bank-statement|tally-data|mixed",
  "detectedDocumentType": "sale_invoice|purchase_invoice|bank_statement|inventory_data|expense_data|staff_data|party_data|backup_data|mixed_data|unknown",
  "summary": "Brief description",
  "confidence": 0.0-1.0,
  "detectedBusiness": "business name if found",
  "detectedGSTIN": "GSTIN if found",
  "importData": {
    "sales": [...],
    "purchases": [...],
    "expenses": [...],
    "products": [...],
    "parties": [...],
    "staff": [...],
    "bankTransactions": [...]
  },
  "warnings": ["issues or assumptions"],
  "suggestions": ["suggestions for user"]
}

Only include non-empty arrays. Be thorough — extract ALL data from the file content. The detectedDocumentType field is REQUIRED — always include it.`

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData()
    const file = formData.get('file') as File | null
    const tenantId = formData.get('tenantId') as string | null
    const importAction = formData.get('action') as string | null

    if (importAction === 'apply' && tenantId) {
      const importDataStr = formData.get('importData') as string
      if (!importDataStr) {
        return NextResponse.json({ error: 'No import data provided' }, { status: 400 })
      }
      return applyImportData(tenantId, JSON.parse(importDataStr))
    }

    // Export merged data to Excel
    if (importAction === 'export-excel' && tenantId) {
      const importDataStr = formData.get('importData') as string
      if (!importDataStr) {
        return NextResponse.json({ error: 'No export data provided' }, { status: 400 })
      }
      return exportMergedExcel(tenantId, JSON.parse(importDataStr))
    }

    if (!file) {
      return NextResponse.json({ error: 'No file uploaded' }, { status: 400 })
    }

    await ensureUploadDir()
    const fileId = randomUUID()
    const fileExt = file.name.split('.').pop() || 'bin'
    const savedFileName = `${fileId}.${fileExt}`
    const filePath = join(UPLOAD_DIR, savedFileName)
    const buffer = Buffer.from(await file.arrayBuffer())
    await writeFile(filePath, buffer)

    console.log(`[AI-Import] Analyzing: ${file.name} (${(buffer.length / 1024).toFixed(1)} KB)`)

    // Fetch tenant info to help AI distinguish sale vs purchase invoices
    let tenantInfo = ''
    let tenantGSTIN = ''
    let tenantName = ''
    if (tenantId) {
      try {
        const tenant = await db.tenant.findUnique({ where: { id: tenantId } })
        if (tenant) {
          tenantGSTIN = tenant.gstNumber || ''
          tenantName = tenant.name || ''
          tenantInfo = `The user's business name is "${tenant.name}"${tenant.gstNumber ? ` with GSTIN ${tenant.gstNumber}` : ''}. Use this to determine if an invoice is a sale (seller = user's business) or purchase (buyer = user's business). IMPORTANT DEFAULT: When uncertain whether an invoice is a sale or purchase, classify it as "purchase_invoice" — because BizBook Pro generates sale invoices internally, and users only import external documents which are almost always purchase invoices from suppliers. Only classify as "sale_invoice" if you are confident the user's business is the seller.`
        }
      } catch (e) {
        console.error('[AI-Import] Failed to fetch tenant for classification context:', e)
      }
    }
    const analysis = await analyzeFileWithAI(file, buffer, tenantInfo)

    // GSTIN-based cross-validation: Override AI classification if GSTINs prove otherwise
    // This is the SAFETY NET — even if AI misclassifies, we can correct based on
    // the actual GSTIN/company name found in the document vs the user's business.
    if (analysis && tenantId) {
      const sellerGst = (analysis.detectedGSTIN || '').trim().toUpperCase()
      const sellerName = (analysis.detectedBusiness || '').trim().toLowerCase()
      const tenantGstNorm = tenantGSTIN.trim().toUpperCase()
      const tenantNameNorm = tenantName.trim().toLowerCase()

      // Helper: check if two business names are similar (fuzzy match)
      const namesMatch = (a: string, b: string): boolean => {
        if (!a || !b) return false
        // Normalize: remove common suffixes and punctuation
        const normalize = (s: string) => s.toLowerCase()
          .replace(/(pvt|private|limited|ltd|llp|inc|co|company|industries|traders|enterprises|corporation|corp|&|and|,|\.|-)/g, '')
          .replace(/\s+/g, '')
          .trim()
        const na = normalize(a)
        const nb = normalize(b)
        if (!na || !nb) return false
        // Exact match after normalization
        if (na === nb) return true
        // One contains the other (e.g., "test business" inside "test business pvt ltd")
        if (na.includes(nb) || nb.includes(na)) return true
        // Both contain at least 6 chars and share a common prefix
        if (na.length >= 6 && nb.length >= 6 && na.substring(0, 6) === nb.substring(0, 6)) return true
        return false
      }

      // v4.9: Spec Section "AI Smart Import Engine" Case C — Bank Statement Mismatch Handling
      // "When processing an uploaded bank statement, the system must run a fuzzy string
      //  comparison check between the statement header's account holder name and the
      //  registered Business Name field in the system settings.
      //  Mismatch Rule: If a variance is detected, do not reject the file.
      //  Intelligent User Prompt: Display a notification banner with action triggers."
      if (analysis.detectedDocumentType === 'bank_statement' && analysis.detectedBusiness) {
        const accountHolderName = analysis.detectedBusiness.trim()
        if (!namesMatch(accountHolderName, tenantName) && accountHolderName.length > 2) {
          analysisResult.warnings.push(
            `BANK_STATEMENT_NAME_MISMATCH: Account holder name on statement ("${accountHolderName}") does not match your company name ("${tenantName}"). ` +
            `This may be the legal Owner/Proprietor name, or an incorrect statement. ` +
            `You can bypass this warning and route to Bank Reconciliation, or assign to Proprietor/Owner Capital Accounts.`
          )
          // Tag the analysis so frontend can show the action triggers
          ;(analysisResult as any).bankStatementMismatch = {
            accountHolderName,
            tenantName,
            actions: [
              { id: 'bypass_reconcile', label: 'Route to Bank Reconciliation Engine', description: 'Bypasses verification to match operational receipts' },
              { id: 'assign_capital', label: 'Assign to Proprietor/Owner Capital Accounts', description: 'Routes entries directly to general journal items' },
            ],
          }
        }
      }

      // Helper: move data from sales array to purchases array (or vice versa)
      const moveSalesToPurchases = () => {
        if (analysis.importData?.sales?.length && !analysis.importData.purchases?.length) {
          analysis.importData.purchases = analysis.importData.sales
          analysis.importData.sales = []
        }
      }
      const movePurchasesToSales = () => {
        if (analysis.importData?.purchases?.length && !analysis.importData.sales?.length) {
          analysis.importData.sales = analysis.importData.purchases
          analysis.importData.purchases = []
        }
      }

      // RULE 1: Seller GSTIN matches tenant's GSTIN → SALE
      // (User's business is the seller — they generated this invoice)
      if (tenantGstNorm && sellerGst && sellerGst === tenantGstNorm) {
        if (analysis.detectedDocumentType === 'purchase_invoice') {
          analysis.warnings = analysis.warnings || []
          analysis.warnings.push(`GSTIN verification: Seller GSTIN matches your business — reclassified from Purchase to Sale invoice.`)
          analysis.detectedDocumentType = 'sale_invoice'
          movePurchasesToSales()
        }
      }
      // RULE 2: Seller GSTIN is DIFFERENT from tenant's GSTIN → PURCHASE
      // (User's business is NOT the seller — they bought from this supplier)
      else if (tenantGstNorm && sellerGst && sellerGst !== tenantGstNorm) {
        if (analysis.detectedDocumentType === 'sale_invoice') {
          analysis.warnings = analysis.warnings || []
          analysis.warnings.push(`GSTIN verification: Seller GSTIN does not match your business — reclassified from Sale to Purchase invoice.`)
          analysis.detectedDocumentType = 'purchase_invoice'
          moveSalesToPurchases()
        }
      }
      // RULE 3: No GSTIN detected, but seller NAME matches tenant name → SALE
      else if (!sellerGst && tenantNameNorm && sellerName && namesMatch(sellerName, tenantNameNorm)) {
        if (analysis.detectedDocumentType === 'purchase_invoice') {
          analysis.warnings = analysis.warnings || []
          analysis.warnings.push(`Business name verification: Seller name matches your business — reclassified from Purchase to Sale invoice.`)
          analysis.detectedDocumentType = 'sale_invoice'
          movePurchasesToSales()
        }
      }
      // RULE 4: No GSTIN detected, but seller NAME is DIFFERENT from tenant name → PURCHASE
      // (Critical fix: previously this case was missing — caused purchase invoices
      // to be misclassified as sale invoices when AI couldn't extract GSTIN)
      else if (!sellerGst && tenantNameNorm && sellerName && !namesMatch(sellerName, tenantNameNorm) && sellerName.length >= 3) {
        if (analysis.detectedDocumentType === 'sale_invoice') {
          analysis.warnings = analysis.warnings || []
          analysis.warnings.push(`Business name verification: Seller name "${analysis.detectedBusiness}" does not match your business "${tenantName}" — reclassified from Sale to Purchase invoice.`)
          analysis.detectedDocumentType = 'purchase_invoice'
          moveSalesToPurchases()
        }
      }
      // RULE 5: Default safety net — if no GSTIN and no business name detected,
      // and AI said "sale_invoice", downgrade confidence and add a warning.
      // BizBook Pro generates sale invoices internally, so importing a "sale"
      // invoice is suspicious — user is likely importing a supplier's invoice.
      else if (!sellerGst && !sellerName && analysis.detectedDocumentType === 'sale_invoice') {
        analysis.warnings = analysis.warnings || []
        analysis.warnings.push(`Could not verify seller identity. Defaulting to PURCHASE invoice (BizBook Pro generates sale invoices internally — imported files are typically supplier purchase invoices).`)
        analysis.detectedDocumentType = 'purchase_invoice'
        moveSalesToPurchases()
      }
    }

    // v4.10: Spec Section 2 Case A — Inventory Cross-Reference Rule
    // "For each extracted line item, the system must search the Products table.
    //  If the name matches an existing string, bind it to its current SKU.
    //  If it does not exist, flag it visually as a [ New Product Detected ] block."
    if (tenantId && analysis.importData) {
      const allLineItems = [
        ...(analysis.importData.sales || []).flatMap((s: any) => s.items || []),
        ...(analysis.importData.purchases || []).flatMap((p: any) => p.items || []),
        ...(analysis.importData.products || []),
      ]

      if (allLineItems.length > 0 && allLineItems.length < 200) {
        try {
          // Get all existing inventory items for this tenant
          const existingItems = await db.inventoryItem.findMany({
            where: { tenantId, isDeleted: false },
            select: { id: true, name: true, sku: true, hsnCode: true },
          })

          const normalizeName = (s: string) => (s || '').toLowerCase().trim().replace(/\s+/g, ' ')

          // Tag each line item with match status
          let newProductCount = 0
          let matchedCount = 0
          for (const item of allLineItems) {
            const itemName = normalizeName(item.name || item.productName || item.description || '')
            if (!itemName) continue

            const match = existingItems.find((ei) => {
              const eiName = normalizeName(ei.name)
              if (!eiName) return false
              if (eiName === itemName) return true
              if (eiName.length >= 6 && itemName.length >= 6 &&
                  (eiName.includes(itemName) || itemName.includes(eiName))) return true
              return false
            })

            if (match) {
              item._matchedInventoryId = match.id
              item._matchedSku = match.sku
              item._matchStatus = 'EXISTING'
              matchedCount++
            } else {
              item._matchStatus = 'NEW_PRODUCT_DETECTED'
              newProductCount++
            }
          }

          if (newProductCount > 0) {
            analysis.warnings = analysis.warnings || []
            analysis.warnings.push(
              `INVENTORY_CROSS_REF: ${newProductCount} new product(s) detected (not in your inventory). ` +
              `${matchedCount} item(s) matched existing inventory. ` +
              `New products will be flagged as [New Product Detected] in the preview — you can register SKUs and HSN codes before saving.`
            )
            ;(analysis as any).inventoryCrossRef = {
              totalItems: allLineItems.length,
              matched: matchedCount,
              newProducts: newProductCount,
            }
          }
        } catch (err: any) {
          console.warn('[AI-Import] Inventory cross-ref failed:', err?.message)
        }
      }
    }

    return NextResponse.json({ success: true, analysis, savedFileName: file.name })
  } catch (error: any) {
    console.error('[AI-Import] Error:', error)
    return NextResponse.json({
      error: error.message || 'Failed to analyze file',
    }, { status: 500 })
  }
}

// ============================================
// Server-side file parsers
// ============================================

async function parseExcelFile(buffer: Buffer): Promise<string> {
  try {
    const XLSX = await import('xlsx')
    const workbook = XLSX.read(buffer, { type: 'buffer' })
    const sheetsData: Record<string, any> = {}
    for (const sheetName of workbook.SheetNames) {
      const sheet = workbook.Sheets[sheetName]
      const jsonData = XLSX.utils.sheet_to_json(sheet, { defval: '' })
      if (jsonData.length > 0) {
        sheetsData[sheetName] = {
          headers: Object.keys(jsonData[0] as Record<string, unknown>),
          totalRows: jsonData.length,
          data: jsonData.length <= 500 ? jsonData : jsonData.slice(0, 500),
          truncated: jsonData.length > 500,
        }
      } else {
        sheetsData[sheetName] = { headers: [], totalRows: 0, data: [] }
      }
    }
    return JSON.stringify(sheetsData, null, 2)
  } catch (error: any) {
    console.error('[AI-Import] Excel parse error:', error.message)
    return `[Excel parsing failed: ${error.message}]`
  }
}

async function parseWordFile(buffer: Buffer): Promise<string> {
  try {
    const mammoth = await import('mammoth')
    const result = await mammoth.extractRawText({ buffer })
    return result.value || '[Empty document]'
  } catch (error: any) {
    console.error('[AI-Import] Word parse error:', error.message)
    try { return buffer.toString('utf-8').replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g, '') || '[Could not parse]' } catch { return '[Word parsing failed]' }
  }
}

async function parsePdfFile(buffer: Buffer): Promise<string> {
  try {
    // pdf-parse v5+ uses named export PDFParse (class), not default
    const pdfModule = await import('pdf-parse')
    const PDFParse = pdfModule.PDFParse || pdfModule.default
    if (!PDFParse) throw new Error('PDFParse not found in module')
    const parser = new PDFParse()
    const data = await parser.parseBuffer(buffer)
    return data.text || '[Empty PDF]'
  } catch (error: any) {
    console.error('[AI-Import] PDF parse error:', error.message)
    // Fallback: try the old-style import
    try {
      const pdfModule = await import('pdf-parse')
      const pdfParse = pdfModule.default || pdfModule
      if (typeof pdfParse === 'function') {
        const data = await pdfParse(buffer)
        return data.text || '[Empty PDF]'
      }
    } catch {}
    return `[PDF text extraction failed: ${error.message}]`
  }
}

function parseCSVToStructured(csv: string, isTSV: boolean): string {
  const separator = isTSV ? '\t' : ','
  const lines = csv.split('\n').filter(l => l.trim())
  if (lines.length === 0) return ''
  const parseRow = (row: string): string[] => {
    const result: string[] = []
    let current = '', inQuotes = false
    for (let i = 0; i < row.length; i++) {
      const ch = row[i]
      if (ch === '"') { if (inQuotes && i + 1 < row.length && row[i + 1] === '"') { current += '"'; i++ } else { inQuotes = !inQuotes } }
      else if (ch === separator && !inQuotes) { result.push(current.trim()); current = '' }
      else { current += ch }
    }
    result.push(current.trim())
    return result
  }
  const headers = parseRow(lines[0])
  const data = lines.slice(1).map(parseRow)
  return JSON.stringify({ headers, totalRows: data.length, sampleRows: data.slice(0, 200), allRows: data.length <= 200 ? data : undefined }, null, 2)
}

// ============================================
// AI analysis engine
// ============================================

async function analyzeFileWithAI(file: File, buffer: Buffer, tenantInfo: string = ''): Promise<any> {
  const zai = await ZAI.create()
  const fileName = file.name.toLowerCase()
  const mimeType = file.type || 'application/octet-stream'
  const systemPrompt = tenantInfo
    ? ANALYSIS_SYSTEM_PROMPT + '\n\nUSER CONTEXT: ' + tenantInfo
    : ANALYSIS_SYSTEM_PROMPT
  let analysisResult: any

  // 1. IMAGES — vision API with base64
  if (mimeType.startsWith('image/') || fileName.match(/\.(png|jpg|jpeg|gif|bmp|webp)$/)) {
    const base64Image = buffer.toString('base64')
    const imageDataUrl = `data:${mimeType};base64,${base64Image}`
    const response = await zai.chat.completions.createVision({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: [
          { type: 'text', text: `Analyze this business document image (${file.name}) and extract all structured data for import into BizBook Pro. Return ONLY valid JSON.` },
          { type: 'image_url', image_url: { url: imageDataUrl } }
        ] }
      ],
      thinking: { type: 'disabled' }
    })
    analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
  }
  // 2. EXCEL — server-side parsing then AI chat
  else if (fileName.match(/\.(xlsx|xls)$/)) {
    const excelData = await parseExcelFile(buffer)
    if (excelData.includes('[Excel parsing failed')) {
      // Fallback: vision API with file_url
      const base64File = buffer.toString('base64')
      const fileDataUrl = `data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,${base64File}`
      try {
        const response = await zai.chat.completions.createVision({
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: [
              { type: 'text', text: `Analyze this Excel file (${file.name}) and extract all structured business data. Return ONLY valid JSON.` },
              { type: 'file_url', file_url: { url: fileDataUrl } }
            ] }
          ],
          thinking: { type: 'disabled' }
        })
        analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
      } catch { analysisResult = null }
    } else {
      const truncatedData = excelData.length > 80000 ? excelData.substring(0, 80000) + '\n... [TRUNCATED]' : excelData
      const response = await zai.chat.completions.create({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Analyze this Excel spreadsheet data (${file.name}) parsed into JSON. Each key is a sheet name with headers and data rows. Extract ALL business data.\n\nParsed data:\n\`\`\`json\n${truncatedData}\n\`\`\`\n\nReturn ONLY valid JSON.` }
        ]
      })
      analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
    }
  }
  // 3. PDF — server-side text extraction then AI chat (fallback: vision)
  else if (mimeType === 'application/pdf' || fileName.endsWith('.pdf')) {
    const pdfText = await parsePdfFile(buffer)
    if (pdfText && !pdfText.includes('[PDF text extraction failed') && pdfText.length > 50) {
      const truncatedText = pdfText.length > 80000 ? pdfText.substring(0, 80000) + '\n... [TRUNCATED]' : pdfText
      const response = await zai.chat.completions.create({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Analyze this PDF document (${file.name}) with extracted text. Extract ALL business data.\n\nText:\n\`\`\`\n${truncatedText}\n\`\`\`\n\nReturn ONLY valid JSON.` }
        ]
      })
      analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
    } else {
      const base64Pdf = buffer.toString('base64')
      const pdfDataUrl = `data:application/pdf;base64,${base64Pdf}`
      try {
        const response = await zai.chat.completions.createVision({
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: [
              { type: 'text', text: `Analyze this PDF (${file.name}) and extract all structured business data. Return ONLY valid JSON.` },
              { type: 'file_url', file_url: { url: pdfDataUrl } }
            ] }
          ],
          thinking: { type: 'disabled' }
        })
        analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
      } catch { analysisResult = null }
    }
  }
  // 4. WORD / RTF — server-side mammoth parsing then AI chat
  else if (fileName.match(/\.(docx|doc|rtf|odt)$/)) {
    const docText = await parseWordFile(buffer)
    if (docText && !docText.includes('[Word parsing failed') && !docText.includes('[Could not parse') && docText.length > 10) {
      const truncatedText = docText.length > 80000 ? docText.substring(0, 80000) + '\n... [TRUNCATED]' : docText
      const response = await zai.chat.completions.create({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Analyze this Word/RTF document (${file.name}) with extracted text. This may contain expenses, purchases, party info, or any business data. Extract ALL business data.\n\nText:\n\`\`\`\n${truncatedText}\n\`\`\`\n\nReturn ONLY valid JSON.` }
        ]
      })
      analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
    } else {
      // Fallback: vision API
      const base64File = buffer.toString('base64')
      const docMimeType = fileName.endsWith('.docx') ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        : fileName.endsWith('.doc') ? 'application/msword'
        : fileName.endsWith('.rtf') ? 'application/rtf'
        : 'application/vnd.oasis.opendocument.text'
      const fileDataUrl = `data:${docMimeType};base64,${base64File}`
      try {
        const response = await zai.chat.completions.createVision({
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: [
              { type: 'text', text: `Analyze this document (${file.name}) and extract ALL business data. Return ONLY valid JSON.` },
              { type: 'file_url', file_url: { url: fileDataUrl } }
            ] }
          ],
          thinking: { type: 'disabled' }
        })
        analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
      } catch { analysisResult = null }
    }
  }
  // 5. CSV, JSON, XML, TXT, TSV — text-based, send to chat
  else {
    let fileContent = ''
    if (fileName.match(/\.(csv|json|txt|xml|tsv)$/)) {
      fileContent = buffer.toString('utf-8')
    }

    let parsedData = ''
    if (fileName.match(/\.(csv|tsv)$/)) {
      parsedData = parseCSVToStructured(fileContent, fileName.endsWith('.tsv'))
    } else if (fileName.endsWith('.json')) {
      try { parsedData = JSON.stringify(JSON.parse(fileContent), null, 2) } catch { parsedData = fileContent }
    } else if (fileName.endsWith('.xml')) {
      parsedData = fileContent
    } else if (fileName.endsWith('.txt')) {
      parsedData = fileContent
    }

    if (parsedData) {
      const truncatedData = parsedData.length > 80000 ? parsedData.substring(0, 80000) + '\n... [TRUNCATED]' : parsedData
      const response = await zai.chat.completions.create({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Analyze this data file (${file.name}, ${buffer.length} bytes) and extract all structured business data.\n\nContent:\n\`\`\`\n${truncatedData}\n\`\`\`\n\nReturn ONLY valid JSON.` }
        ]
      })
      analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
    } else {
      // Unknown binary — try vision API
      const base64File = buffer.toString('base64')
      const fileDataUrl = `data:${mimeType};base64,${base64File}`
      try {
        const response = await zai.chat.completions.createVision({
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: [
              { type: 'text', text: `Analyze this file (${file.name}, ${mimeType}) and extract business data. Return ONLY valid JSON.` },
              { type: 'file_url', file_url: { url: fileDataUrl } }
            ] }
          ],
          thinking: { type: 'disabled' }
        })
        analysisResult = parseAIResponse(response.choices[0]?.message?.content || '')
      } catch { analysisResult = null }
    }
  }

  if (!analysisResult) {
    analysisResult = {
      fileName: file.name, fileType: 'unknown',
      summary: 'Could not analyze this file. Try CSV, Excel, or image format.',
      confidence: 0, importData: {},
      warnings: ['AI analysis could not parse the file'],
      suggestions: ['Try CSV, JSON, or image format', 'Ensure Excel files are .xlsx', 'For PDFs, use text-based rather than scanned']
    }
  }

  analysisResult.fileName = analysisResult.fileName || file.name
  analysisResult.importData = analysisResult.importData || {}
  analysisResult.warnings = analysisResult.warnings || []
  analysisResult.suggestions = analysisResult.suggestions || []
  // Ensure detectedDocumentType is present; infer from fileType if missing
  // IMPORTANT: Do NOT map generic "invoice" to "sale_invoice" — an invoice
  // could be a sale OR a purchase. Use importData to disambiguate.
  if (!analysisResult.detectedDocumentType) {
    const ft = (analysisResult.fileType || '').toLowerCase()

    // First, check importData arrays to determine the actual type from data
    const populatedKeys = Object.keys(analysisResult.importData || {}).filter(k => Array.isArray(analysisResult.importData[k]) && analysisResult.importData[k].length > 0)
    const hasSales = populatedKeys.includes('sales')
    const hasPurchases = populatedKeys.includes('purchases')
    const dataMap: Record<string, string> = { sales: 'sale_invoice', purchases: 'purchase_invoice', bankTransactions: 'bank_statement', products: 'inventory_data', expenses: 'expense_data', staff: 'staff_data', parties: 'party_data' }

    if (ft.includes('sale') && !ft.includes('purchase')) {
      // fileType says "sale" — but verify with importData, as AI often misclassifies
      // purchase invoices as "sale" type. If purchases data exists, it's likely a purchase.
      if (hasPurchases && !hasSales) {
        analysisResult.detectedDocumentType = 'purchase_invoice'
        analysisResult.warnings.push('File type indicated "sale" but data suggests this is a Purchase invoice. Reclassified accordingly.')
      } else if (hasSales) {
        // Sales data exists — classify as sale, but cross-validation in the
        // main handler will override this if GSTIN/name doesn't match tenant.
        analysisResult.detectedDocumentType = 'sale_invoice'
      } else {
        // No sales AND no purchases data — default to PURCHASE because
        // sale invoices are GENERATED by BizBook Pro (not imported).
        // Users import external supplier invoices, which are PURCHASE invoices.
        analysisResult.detectedDocumentType = 'purchase_invoice'
        analysisResult.warnings.push('File type indicated "sale" but no sale data was extracted. Defaulted to Purchase invoice (BizBook Pro generates sale invoices internally — imported files are typically supplier purchase invoices).')
      }
    } else if (ft.includes('purchase') || ft.includes('supplier')) {
      analysisResult.detectedDocumentType = 'purchase_invoice'
    } else if (ft.includes('bank')) {
      analysisResult.detectedDocumentType = 'bank_statement'
    } else if (ft.includes('product') || ft.includes('inventory')) {
      analysisResult.detectedDocumentType = 'inventory_data'
    } else if (ft.includes('expense')) {
      analysisResult.detectedDocumentType = 'expense_data'
    } else if (ft.includes('tally') || ft.includes('backup')) {
      analysisResult.detectedDocumentType = 'backup_data'
    } else if (ft.includes('mixed')) {
      analysisResult.detectedDocumentType = 'mixed_data'
    } else if (ft.includes('invoice')) {
      // Generic "invoice" — ambiguous. Default to PURCHASE because:
      // - Sale invoices are GENERATED by BizBook Pro (user doesn't import them)
      // - Users IMPORT external supplier invoices, which are PURCHASE invoices
      // - Only classify as sale_invoice if tenant GSTIN matches the seller
      if (hasPurchases && !hasSales) {
        analysisResult.detectedDocumentType = 'purchase_invoice'
      } else if (hasSales && !hasPurchases) {
        // AI put data in sales array — but this could be wrong (common misclassification).
        // Still classify as sale_invoice but add a warning for user verification.
        analysisResult.detectedDocumentType = 'sale_invoice'
        analysisResult.warnings.push('Invoice classified as Sale — please verify this is not a Purchase invoice from a supplier. Sale invoices are normally generated by BizBook Pro, not imported.')
      } else if (hasSales && hasPurchases) {
        // Both sales AND purchases present — don't guess
        analysisResult.detectedDocumentType = 'mixed_data'
      } else {
        // No sales or purchase data to infer from — default to purchase
        // because imported invoices are almost always from external suppliers
        analysisResult.detectedDocumentType = 'purchase_invoice'
        analysisResult.warnings.push('Invoice type ambiguous — defaulted to Purchase. Imported invoices are typically from external suppliers. Please verify manually.')
      }
    } else {
      // No fileType match — infer from populated importData keys
      if (populatedKeys.length === 1) {
        analysisResult.detectedDocumentType = dataMap[populatedKeys[0]] || 'unknown'
      } else if (populatedKeys.length > 1) {
        analysisResult.detectedDocumentType = 'mixed_data'
      } else {
        analysisResult.detectedDocumentType = 'unknown'
      }
    }
  }
  return analysisResult
}

function parseAIResponse(content: string): any {
  let jsonStr = content.trim()
  const codeBlockMatch = jsonStr.match(/```(?:json)?\s*([\s\S]*?)```/)
  if (codeBlockMatch) jsonStr = codeBlockMatch[1].trim()
  try { return JSON.parse(jsonStr) } catch {
    const jsonMatch = jsonStr.match(/\{[\s\S]*\}/)
    if (jsonMatch) {
      try { return JSON.parse(jsonMatch[0]) } catch {
        try { return JSON.parse(jsonMatch[0].replace(/,\s*([}\]])/g, '$1')) } catch { return null }
      }
    }
    return null
  }
}

// ============================================
// Normalize AI output field names to match Prisma schema
// ============================================

function normalizeSaleData(sale: any) {
  return {
    date: sale.date ? new Date(sale.date) : new Date(),
    invoiceNumber: sale.invoiceNumber || `AI-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    partyName: sale.partyName || 'Walk-in Customer',
    partyAddress: sale.partyAddress || sale.partyAddress || null,
    partyGst: sale.partyGst || sale.partyGstin || null,
    items: typeof sale.items === 'string' ? sale.items : JSON.stringify(sale.items || []),
    subtotal: Number(sale.subtotal || sale.total || 0),
    gstAmount: Number(sale.gstAmount || sale.gstTotal || 0),
    totalAmount: Number(sale.totalAmount || sale.grandTotal || sale.total || 0),
    paymentStatus: normalizeSalePaymentStatus(sale.paymentStatus || sale.status),
    amountReceived: Number(sale.amountReceived || sale.amountPaid || 0),
    amountPaid: Number(sale.amountPaid || sale.amountReceived || 0),
    notes: sale.notes || null,
  }
}

function normalizeSalePaymentStatus(status: string): string {
  if (!status) return 'PENDING'
  const s = status.toUpperCase().trim()
  if (s === 'PAID' || s === 'RECEIVED' || s === 'CONFIRMED') return 'RECEIVED'
  if (s === 'PARTIAL') return 'PARTIAL'
  if (s === 'UNPAID' || s === 'PENDING') return 'PENDING'
  return 'PENDING'
}

function normalizePurchaseData(purchase: any) {
  return {
    date: purchase.date ? new Date(purchase.date) : new Date(),
    invoiceNumber: purchase.invoiceNumber || `AI-P-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    partyName: purchase.partyName || 'Unknown Supplier',
    partyAddress: purchase.partyAddress || purchase.partyAddress || null,
    partyGst: purchase.partyGst || purchase.partyGstin || null,
    items: typeof purchase.items === 'string' ? purchase.items : JSON.stringify(purchase.items || []),
    subtotal: Number(purchase.subtotal || purchase.total || 0),
    gstAmount: Number(purchase.gstAmount || purchase.gstTotal || 0),
    totalAmount: Number(purchase.totalAmount || purchase.grandTotal || purchase.total || 0),
    paymentStatus: normalizePurchasePaymentStatus(purchase.paymentStatus || purchase.status),
    amountPaid: Number(purchase.amountPaid || 0),
    notes: purchase.notes || null,
  }
}

function normalizePurchasePaymentStatus(status: string): string {
  if (!status) return 'UNPAID'
  const s = status.toUpperCase().trim()
  if (s === 'PAID' || s === 'CONFIRMED') return 'PAID'
  if (s === 'PARTIAL') return 'PARTIAL'
  if (s === 'UNPAID' || s === 'PENDING') return 'UNPAID'
  return 'UNPAID'
}

function normalizeProductData(product: any) {
  return {
    name: product.name || 'Unknown Product',
    sku: product.sku || product.barcode || null,
    category: product.category || null,
    hsnCode: product.hsnCode || product.hsn || null,
    unit: product.unit || 'PCS',
    brand: product.brand || null,
    itemType: product.itemType || (product.type === 'RAW_MATERIAL' ? 'RAW_MATERIAL' : 'FINISHED_PRODUCT'),
    purchasePrice: Number(product.purchasePrice || product.purchaseRate || product.costPrice || 0),
    salePrice: Number(product.salePrice || product.saleRate || product.sellingPrice || 0),
    mrp: Number(product.mrp || 0) || null,
    openingStock: Number(product.openingStock || product.stock || 0),
    currentStock: Number(product.currentStock || product.stock || 0),
    minStock: Number(product.minStock || product.reorderLevel || 0),
    gstRate: Number(product.gstRate || 18),
    value: Number(product.value || 0),
  }
}

function normalizeBankTxnData(txn: any) {
  // AI may return amount+type or deposit+withdrawal — normalize to deposit+withdrawal
  let deposit = Number(txn.deposit || 0)
  let withdrawal = Number(txn.withdrawal || 0)
  const amount = Number(txn.amount || 0)

  if (deposit === 0 && withdrawal === 0 && amount !== 0) {
    const type = (txn.type || '').toUpperCase()
    if (type === 'CREDIT' || type === 'DEPOSIT' || type === 'IN' || amount > 0) {
      deposit = Math.abs(amount)
      withdrawal = 0
    } else {
      withdrawal = Math.abs(amount)
      deposit = 0
    }
  }

  return {
    date: txn.date ? new Date(txn.date) : new Date(),
    description: txn.description || txn.narration || 'Imported transaction',
    deposit,
    withdrawal,
    balance: Number(txn.balance || 0),
    reference: txn.reference || txn.ref || null,
    category: txn.category || null,
    bankName: txn.bankName || null,
    accountNumber: txn.accountNumber || txn.accountNo || null,
  }
}

function normalizeStaffData(s: any) {
  return {
    name: s.name || 'Unknown Staff',
    phone: s.phone || null,
    email: s.email || null,
    role: s.role || s.designation || 'Staff',
    department: s.department || null,
    salary: Number(s.salary || 0),
    address: s.address || null,
    aadhaar: s.aadhaar || s.aadhar || null,
    pan: s.pan || null,
  }
}

function normalizeExpenseData(expense: any) {
  return {
    date: expense.date ? new Date(expense.date) : new Date(),
    description: expense.description || 'Imported expense',
    category: expense.category || 'General',
    amount: Number(expense.amount || 0),
    paymentMode: expense.paymentMode || 'CASH',
    reference: expense.reference || null,
    notes: expense.notes || null,
  }
}

// ============================================
// Apply imported data to database
// ============================================

async function applyImportData(tenantId: string, importData: any) {
  const results: any = { sales: 0, purchases: 0, expenses: 0, products: 0, parties: 0, staff: 0, bankTransactions: 0, errors: [] as string[] }

  try {
    // Parties — upsert by name
    if (importData.parties?.length > 0) {
      for (const party of importData.parties) {
        try {
          const existing = await db.party.findFirst({ where: { name: party.name || 'Unknown Party', tenantId, isDeleted: false } })
          if (existing) {
            await db.party.update({ where: { id: existing.id }, data: {
              phone: party.phone ?? existing.phone,
              email: party.email ?? existing.email,
              address: party.address ?? existing.address,
              gstNumber: (party.gstNumber || party.gstin) ?? existing.gstNumber,
              panNumber: party.panNumber ?? existing.panNumber,
              type: party.type ?? existing.type,
            } })
          } else {
            await db.party.create({ data: {
              name: party.name || 'Unknown Party',
              type: party.type || 'BOTH',
              phone: party.phone || null,
              email: party.email || null,
              address: party.address || null,
              gstNumber: party.gstNumber || party.gstin || null,
              panNumber: party.panNumber || null,
              openingBalance: Number(party.openingBalance || 0),
              currentBalance: Number(party.openingBalance || 0),
              tenantId,
            } })
          }
          results.parties++
        } catch (e: any) { results.errors.push(`Party "${party.name}": ${e.message}`) }
      }
    }

    // Products — upsert by name
    if (importData.products?.length > 0) {
      for (const product of importData.products) {
        try {
          const normalized = normalizeProductData(product)
          const existing = await db.inventoryItem.findFirst({ where: { name: normalized.name, tenantId, isDeleted: false } })
          if (existing) {
            await db.inventoryItem.update({ where: { id: existing.id }, data: {
              sku: normalized.sku ?? existing.sku,
              category: normalized.category ?? existing.category,
              hsnCode: normalized.hsnCode ?? existing.hsnCode,
              unit: normalized.unit ?? existing.unit,
              brand: normalized.brand ?? existing.brand,
              purchasePrice: normalized.purchasePrice ?? existing.purchasePrice,
              salePrice: normalized.salePrice ?? existing.salePrice,
              mrp: normalized.mrp ?? existing.mrp,
              gstRate: normalized.gstRate ?? existing.gstRate,
              currentStock: normalized.currentStock ?? existing.currentStock,
            } })
          } else {
            await db.inventoryItem.create({ data: { ...normalized, tenantId } })
          }
          results.products++
        } catch (e: any) { results.errors.push(`Product "${product.name}": ${e.message}`) }
      }
    }

    // Sales — skip duplicates by invoice number
    if (importData.sales?.length > 0) {
      for (const sale of importData.sales) {
        try {
          const normalized = normalizeSaleData(sale)
          const existing = await db.sale.findFirst({ where: { invoiceNumber: normalized.invoiceNumber, tenantId, isDeleted: false } })
          if (existing) { results.errors.push(`Sale "${normalized.invoiceNumber}": Already exists, skipped`); continue }
          await db.sale.create({ data: { ...normalized, tenantId } })
          results.sales++
        } catch (e: any) { results.errors.push(`Sale "${sale.invoiceNumber}": ${e.message}`) }
      }
    }

    // Purchases — skip duplicates by invoice number
    if (importData.purchases?.length > 0) {
      for (const purchase of importData.purchases) {
        try {
          const normalized = normalizePurchaseData(purchase)
          const existing = await db.purchase.findFirst({ where: { invoiceNumber: normalized.invoiceNumber, tenantId, isDeleted: false } })
          if (existing) { results.errors.push(`Purchase "${normalized.invoiceNumber}": Already exists, skipped`); continue }
          await db.purchase.create({ data: { ...normalized, tenantId } })
          results.purchases++
        } catch (e: any) { results.errors.push(`Purchase "${purchase.invoiceNumber}": ${e.message}`) }
      }
    }

    // Expenses
    if (importData.expenses?.length > 0) {
      for (const expense of importData.expenses) {
        try {
          const normalized = normalizeExpenseData(expense)
          await db.expense.create({ data: { ...normalized, tenantId } })
          results.expenses++
        } catch (e: any) { results.errors.push(`Expense "${expense.description}": ${e.message}`) }
      }
    }

    // Staff
    if (importData.staff?.length > 0) {
      for (const s of importData.staff) {
        try {
          const normalized = normalizeStaffData(s)
          await db.staff.create({ data: { ...normalized, tenantId } })
          results.staff++
        } catch (e: any) { results.errors.push(`Staff "${s.name}": ${e.message}`) }
      }
    }

    // Bank Transactions
    if (importData.bankTransactions?.length > 0) {
      for (const txn of importData.bankTransactions) {
        try {
          const normalized = normalizeBankTxnData(txn)
          await db.bankTransaction.create({ data: { ...normalized, tenantId } })
          results.bankTransactions++
        } catch (e: any) { results.errors.push(`Bank txn: ${e.message}`) }
      }
    }

    const totalImported = results.sales + results.purchases + results.expenses + results.products + results.parties + results.staff + results.bankTransactions
    return NextResponse.json({ success: true, message: `Imported ${totalImported} records successfully`, results })
  } catch (error: any) {
    console.error('Apply import error:', error)
    return NextResponse.json({ success: false, error: error.message, results }, { status: 500 })
  }
}

// ============================================
// Export merged data as Excel file
// ============================================

async function exportMergedExcel(tenantId: string, importData: any) {
  try {
    const XLSX = await import('xlsx')
    const tenant = await db.tenant.findUnique({ where: { id: tenantId } })
    const wb = XLSX.utils.book_new()

    if (importData.parties?.length > 0) {
      const ws = XLSX.utils.json_to_sheet(importData.parties.map((p: any) => ({ Name: p.name, Type: p.type, Phone: p.phone, Email: p.email, GSTIN: p.gstNumber || p.gstin, Address: p.address, OpeningBalance: p.openingBalance })))
      XLSX.utils.book_append_sheet(wb, ws, 'Parties')
    }
    if (importData.products?.length > 0) {
      const ws = XLSX.utils.json_to_sheet(importData.products.map((p: any) => ({ Name: p.name, SKU: p.sku || p.barcode, Category: p.category, HSN: p.hsnCode || p.hsn, Unit: p.unit, PurchasePrice: p.purchasePrice || p.purchaseRate, SalePrice: p.salePrice || p.saleRate, MRP: p.mrp, GSTRate: p.gstRate, Stock: p.currentStock || p.stock, Brand: p.brand })))
      XLSX.utils.book_append_sheet(wb, ws, 'Products')
    }
    if (importData.sales?.length > 0) {
      const ws = XLSX.utils.json_to_sheet(importData.sales.map((s: any) => ({ Date: s.date, InvoiceNo: s.invoiceNumber, Party: s.partyName, Subtotal: s.subtotal || s.total, GST: s.gstAmount || s.gstTotal, Total: s.totalAmount || s.grandTotal, PaymentStatus: s.paymentStatus || s.status, Items: typeof s.items === 'string' ? s.items : JSON.stringify(s.items || []) })))
      XLSX.utils.book_append_sheet(wb, ws, 'Sales')
    }
    if (importData.purchases?.length > 0) {
      const ws = XLSX.utils.json_to_sheet(importData.purchases.map((p: any) => ({ Date: p.date, InvoiceNo: p.invoiceNumber, Party: p.partyName, Subtotal: p.subtotal || p.total, GST: p.gstAmount || p.gstTotal, Total: p.totalAmount || p.grandTotal, PaymentStatus: p.paymentStatus || p.status, Items: typeof p.items === 'string' ? p.items : JSON.stringify(p.items || []) })))
      XLSX.utils.book_append_sheet(wb, ws, 'Purchases')
    }
    if (importData.expenses?.length > 0) {
      const ws = XLSX.utils.json_to_sheet(importData.expenses.map((e: any) => ({ Date: e.date, Description: e.description, Category: e.category, Amount: e.amount, PaymentMode: e.paymentMode, Reference: e.reference })))
      XLSX.utils.book_append_sheet(wb, ws, 'Expenses')
    }
    if (importData.bankTransactions?.length > 0) {
      const ws = XLSX.utils.json_to_sheet(importData.bankTransactions.map((t: any) => ({ Date: t.date, Description: t.description, Deposit: t.deposit || (t.type === 'CREDIT' ? t.amount : 0), Withdrawal: t.withdrawal || (t.type === 'DEBIT' ? t.amount : 0), Balance: t.balance, Reference: t.reference, Category: t.category })))
      XLSX.utils.book_append_sheet(wb, ws, 'Bank Transactions')
    }
    if (importData.staff?.length > 0) {
      const ws = XLSX.utils.json_to_sheet(importData.staff.map((s: any) => ({ Name: s.name, Phone: s.phone, Email: s.email, Role: s.role, Department: s.department, Salary: s.salary })))
      XLSX.utils.book_append_sheet(wb, ws, 'Staff')
    }

    // If no sheets, create empty summary
    if (wb.SheetNames.length === 0) {
      const ws = XLSX.utils.aoa_to_sheet([['No data to export']])
      XLSX.utils.book_append_sheet(wb, ws, 'Summary')
    }

    const excelBuffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })
    const fileName = `${tenant?.name || 'BizBook'}_AI_Import.xlsx`

    return new NextResponse(excelBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${encodeURIComponent(fileName)}"`,
      },
    })
  } catch (error: any) {
    console.error('[AI-Import] Excel export error:', error)
    return NextResponse.json({ error: error.message || 'Failed to export Excel' }, { status: 500 })
  }
}
